### ISSUE TITLE
"Stardew Valley is not installed in the chosen directory" error

### ISSUE THREAD

**Issue by electric-snake** [coder0987/StardewValleyTranslationHelper#1]
Hi, very excited for this project! However, when I try to run the program, I get this error: "Stardew Valley is not installed in the chosen directory. Please install Stardew Valley." Stardew is installed in the directory and I have run it directly from a file within that directory, so I'm not sure what the program is looking for. 

I'm using manjaro linux and tried opening the program with OpenJDK Java 22 Runtime (I know almost nothing about java so I don't know if I need to be using a different one to get it to work). I tried all three versions of the program in the releases and all of them gave the same error. I also tried putting the Stardew install in a different directory and got the same error

**Comment by coder0987** [comment]
@electric-snake thank you for the feedback!
I haven't tested this project on Linux yet. I'll try replicating your setup and see what errors I get. Most likely it's file extension issue

**Comment by coder0987** [comment]
I've just released v0.2.0 which should fix your issue on Linux devices
If you run into another other issues feel free to create another issue and let me know!
(In case you were wondering- it was a file extension thing at first, but there were loads of other issues too! I've also added some instructions for manually installing in case permissions don't work out well on Linux devices, since that was one of the main issues I ran into in testing)
